export enum ActionType {
   ADD_TO_CART = "ADD_TO_CART",
   REMOVE_FROM_CART = "REMOVE_FROM_CART",
   OPEN_CART_MODAL = "OPEN_CART_MODAL",
   CLOSE_CART_MODAL = "CLOSE_CART_MODAL",
   UPDATE_CART = "UPDATE_CART",
}
